name: Docker CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linting:
    name: Code Formatting Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run clang-format Linter
        uses: DoozyX/clang-format-lint-action@v0.17
        with:
          source: './src'
          extensions: 'h,c'
          style: Google 
          failOnWarning: true

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: linting 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ultimate-tic-tac-toe:latest

      - name: Basic artifact check
        run: |
          docker run --rm ultimate-tic-tac-toe:latest sh -c "test -f /app/public/index.html"
          echo "Build artifact 'index.html' found successfully."