name: Docker CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ultimate-tic-tac-toe:latest

      - name: Basic artifact check
        run: |
          docker run --rm ultimate-tic-tac-toe:latest sh -c "test -f /app/public/index.html"
          echo "Build artifact 'index.html' found successfully."